### ISSUE TITLE
not a issue

### ISSUE THREAD

**Issue by Artinnavidgoli** [sweakpl/unlock-master#1]
can you please upload the compiled version ? 🙃

**Comment by sweakpl** [comment]
Hey, in the README I have left a small note (sorry, it really might have been difficult to notice) that this project is still in the development phase, hence there's no APK of the application yet. It will be available as soon as I consider the project to be stable.

**Comment by Artinnavidgoli** [comment]
Hey, I really appreciate your reply. It was very helpful and informative. I'm sorry if I'm bothering you too much with my questions. I know you're probably busy and have other things to do. I hope you don't mind me asking for your opinion on this topic.

**Comment by IzzySoft** [comment]
Btw, since 10/2023 the app is also [available via the IzzyOnDroid F-Droid repo](https://apt.izzysoft.de/packages/com.sweak.unlockmaster), thanks to your making the APK available here (which is where the IoD updater picks it from). @sweakpl be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to that URL, so that Play badge does not feel too lonely. Looks like unfortunately your RFP at F-Droid isn't processed yet, but many folks also have the IoD repo enabled…
